### PR TITLE
Ready to go live!

### PR DESCRIPTION
**Pull request by gdancik**

### CODE REVIEW

**Comment by power-serge** [comment]
Prof. Dancik I am wondering if I can cherry pick what I merge. 
I see that you added the whole directory structure. 
I usually don't commit the binary file (.RData file) or the tmp directory. 
I have a dedicated branch for the html, css, and javascript (gh-deploy).

Also, I see that both the BuildCountiesWebsite.R and .sh file have instructions to push. Is it safe to assume that they both do the same. I tried to automate in Git Bash but it get errors there that I don't get in the Command Line.

Anyway, I'll see if I can cherry pick, if not I might just merge the whole thing eventually.

**Comment by gdancik** [comment]
You can cherry pick what you merge, using the git command line tool (https://mattstauffer.com/blog/how-to-merge-only-specific-commits-from-a-pull-request/). 

Really, the only commit you need to merge is the fist one, which updates the Home.rmd and Template.rmd files to use the 7 day averages for the gauges. There is also a minor update to the size of some of the figures.

On my repository, I will continue to update the html files since that is part of the pipeline for updating the webpage, but you don't need that. I also want to keep the updated RData file because that gives us a copy of the data files over time, in case I want to go back to look at a particular time period.

The instructions for pushing should only be in the .sh file (and you don't need this unless you want to have it). The push instructions in BuildCountiesWebsite.R should have been removed but I realized that the push to do that did not go through previously (though it has now).

**Comment by power-serge** [comment]
Professor, I pulled the changes locally, performed a soft reset on your pull request, eliminated the files I didn't need, and merged the changes I needed to master in commit:
809af831bdd599bffe94c163f4844ee2ecb8db1c

Therefore I am closing this pull request.
Thanks for the code.

**Comment by gdancik** [comment]
Sounds good!

**Pull request closed without merging**
